name: lesto
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  get_storage: 2.1.1
  intl: ^0.19.0
  flutter_speed_dial: ^7.0.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  csc_picker: ^0.2.7
  flutter_svg: ^2.0.10+1
  date_picker_plus: ^4.1.0
  video_player: ^2.9.1
  otp_pin_field: ^1.3.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/AppIcon.png"

flutter:
  assets:
    - assets/
    - assets/images/
    - assets/icons/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Kurale/Kurale-Regular.ttf
    - family: PoppinsRegular
      fonts:
        - asset: assets/fonts/Kurale/Kurale-Regular.ttf
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Moonjelly/Moonjelly-Light.otf
    - family: GilroyRegular
      fonts:
        - asset: assets/fonts/Moonjelly/Moonjelly-Light.otf
    - family: GilroyMedium
      fonts:
        - asset: assets/fonts/Moonjelly/Moonjelly-Bold.otf
    - family: GilroySemi
      fonts:
        - asset: assets/fonts/Moonjelly/Moonjelly-Bold.otf
    - family: GilroyBold
      fonts:
        - asset: assets/fonts/Moonjelly/Moonjelly-Bold.otf
  uses-material-design: true
